server:
  port: 8080

spring:
  application:
    name: shortzen-api

  datasource:
    url: jdbc:postgresql://localhost:5433/shortzen
    username: shortzen
    password: shortzen123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework: INFO